### ISSUE TITLE
name, numberがnullのときにアプリが強制終了する

### ISSUE THREAD

**Issue by touyu** [payjp/payjp-ios#1]
createTokenを実行した際、

> fatalerror: 'try!' expression unexpectedly raised an error: DecodeError.missingKeyPath(KeyPath(["name"]))

と表示されてしまい、アプリが強制終了します。

Cardクラスのname, numberをオプショナル型にすべきではないでしょうか

**Comment by laiso** [comment]
修正のプルリクエストありがとうございます、取り込まされていただきました。

本件はそもそも未リリースの試験的な変更を master ブランチへコミットしていたことが原因でした。
今後のリポジトリの運用フローを見直す所存です。
