### ISSUE TITLE
カード名義入力時日本語キーボードにa/Aで大文字変換できない

### ISSUE THREAD

**Issue by EndouMari** [payjp/payjp-ios#70]
# issue
カード名義の入力時に日本語キーボードを使用して大文字変換をしようとすると以下のスクリーンショットのようになります。

<img src="https://user-images.githubusercontent.com/8034270/144535693-12b4dda9-5bd2-4757-8257-934a15224fdb.png" height=300>

# description
shouldChangeCharactersInのデリゲートを使用して入力された文字列を変換していますが、その際に大文字・小文字変換を考慮する必要があると思います。
https://github.com/payjp/payjp-ios/blob/master/Sources/Views/CardFormView.swift#L474
<入力文字列と変換後のnewText>
```
pajp: string t - newText t
pajp: string ↨ - newText t↨
pajp: string a - newText t↨a
pajp: string ↨ - newText t↨a↨
pajp: string n - newText t↨a↨n
pajp: string ↨ - newText t↨a↨n↨
```

shouldChangeCharactersInでは独自で大文字・小文字変換が必要になりそうですが、textViewのeditingChangedであれば入力変換された文字列が取得できると思いますので、そちらを使うのがいいのではないでしょうか？

**Comment by yatatsu** [comment]
フィードバックありがとうございます。
ご指摘通りshouldChangeCharactersInRangeを使うのは変換に課題があるため、不具合の修正と合わせて改修したい考えです。

**Comment by yatatsu** [comment]
こちらの問題について #71 にて修正し、https://github.com/payjp/payjp-ios/releases/tag/1.6.2 にてリリースしました。
